// Copyright 2017-2023 @soul-wallet/chain-list authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@soul-wallet/chain-list', path: 'auto', type: 'auto', version: '1.0.0' };
